RT-12219: Create skeleton for Tradeline lib; Added TradelineClient an…
levelcredit/tradeline-php pull request #1
Opened 2021-01-14 18:38 UTC by yurez

…d response models  AuthenticateResponse and OrderResponse

2021-01-21 20:30 UTC, yurez commented on composer.json
> +    "levelcredit/levelcredit-api-php": "dev-master"
Will be change when add version to github on next pull-request

2021-01-22 07:32 UTC, caryp requested changes
Looking good!  A couple complexities that I suggest we remove.

2021-01-22 07:32 UTC, caryp commented on composer.json
> +  "description": "LevelCredit Tradeline API Client Library for PHP",
please rename "API Client Library" to "SDK".

2021-01-22 07:32 UTC, caryp commented on src/TradelineClient.php
> +        string $fileLogPath = '',
They will want to tie in their own logger so should take a standard `LoggerInterface` instead of a file location.

2021-01-22 07:32 UTC, caryp commented on src/TradelineClient.php
> +     * Be careful on call this method in api client will be recreate DefaultLogHandler with default parameters
Seems scary. How can I be careful?  When would I not want to use this?

2021-01-22 07:32 UTC, caryp commented on src/TradelineClient.php
> +        );
why not just `$this->apiClient->setLogger($logger)`?  This seems unnecessarily complicated.

2021-01-22 07:32 UTC, caryp commented on src/TradelineClient.php
> +    public function setApiClient(LevelCreditApiClient $apiClient): self
This SDK should initialize and use the api client internally.  I dont think we want to support the client of this SDK interacting directly with the apiClient li.  The idea is to be able to replace the underlying API client it without client needing to change their code.

What default parameters do you expect them to need to change?

2021-01-22 12:15 UTC, tatyana-shmatchenko commented on src/TradelineClient.php
> +        );
Looks like this part requires a live discussion.
To completely understand what exactly needs to be here, we need to know what to do with log formatting.
SDK has a requirement:
> Need to be able to log request/response (with sensitive values sanitized).

We understood it so that SDK should care about formatting and using the log handler is the way to implement that requirement. 
Let's discuss several unknowns:
1. Should we implement sensitive data sanitization?
2. If the above is yes, should we implement the ability to switch off sensitive data sanitization?
3. Should we allow to change the log template formatting?

2021-01-22 12:15 UTC, tatyana-shmatchenko commented on src/TradelineClient.php
> +     * Be careful on call this method in api client will be recreate DefaultLogHandler with default parameters
This will be dropped together with `setApiClient` method.

2021-01-23 01:20 UTC, caryp requested changes
Thank your for the thoughtful responses.  We would like to give a version of this SDK to zego for review.  Can wait in the setLogger decision by creating a new tick for that, but make the other changes?

2021-01-23 01:20 UTC, caryp commented on src/TradelineClient.php
> +        string $fileLogPath = '',
This will always be used as a library, if no logger is set then I would expect it to log to STDOUT.

2021-01-23 01:20 UTC, caryp commented on src/TradelineClient.php
> +        );
Ah, so does the "be careful" in the comment above mean "be careful, you will lose data sanitization and sensitive data will be logged"?

2021-01-23 01:20 UTC, caryp commented on src/TradelineClient.php
> +    public function setApiClient(LevelCreditApiClient $apiClient): self
I see.  I typically do not let testing dictate my interfaces.  Can we make it protected/private and then do something like this to have the ability to call in a test? https://stackoverflow.com/questions/249664/best-practices-to-test-protected-methods-with-phpunit

We should also add a comment that this is added for testing purposes to make it clear.

2021-01-23 01:20 UTC, caryp commented on src/TradelineClient.php
> +        );
1) yes. but in at the api client level
2) not a requirement, and probably a bad idea for clients to do so.
3) probably a good idea!

2021-01-27 13:04 UTC, tatyana-shmatchenko requested changes
Looking great @yurez !

2021-01-27 15:08 UTC, tatyana-shmatchenko approved these changes

2021-01-27 15:09 UTC, merged